### PR TITLE
Update ruleset.xml

### PR DESCRIPTION
**Pull request by rixbeck**
Bolt.Whitespace.ConcatenationSpacing does his work right but some kinda fallback happens to the default rule so phpcs says: 'Concat operator must not be surrounded by spaces' until this patch.

### CODE REVIEW

**Comment by rarila** [comment]
Until now the wanted setting was one space. But as the Symfony setting is no space, I planned to change this. There was some discussion about this on irc and the result was mostly "I don't care". I didn't tackle this sofar as there were some major branches open at that time.

**Comment by GwendolenLynch** [comment]
The discussion was 50% against, 25% don't care and 25% for… Just sayin' :stuck_out_tongue_winking_eye:

**Comment by rarila** [comment]
I remember that this "discussion" before it came to an end soon drifted into fun so that there wasn't really a result.

**Comment by rixbeck** [comment]
Okay, but actual state a bit confusing. If no space then "1 space before 
and after required", after correction "no spaces around should be" comes 
up. :-)

Sent with AquaMail for Android
http://www.aqua-mail.com

**Comment by rarila** [comment]
Ok, that's another problem then. bolt/codingstyle needs to be tagged and that version needs to be required in Bolts composer.json. (no space was switched on with #3)

**Comment by rarila** [comment]
So let's tackle that again, vote, change it or not, tag it, use it in Bolt.

To ease things everyone with more than 425 commits on Bolt should vote, others welcome of course.

pinging @GawainLynch , @bobdenotter , @rossriley, @CarsonF
- [ ] One space, Bolts **current** style (`$foo = 'bar' . $bar;`)
- [ ] No space, Symfony style (`$foo = 'bar'.$bar;`)

**Comment by GwendolenLynch** [comment]
Space… The final frontier…
- [x] One space, Bolts **current** style (`$foo = 'bar' . $bar;`)
- [ ] No space, Symfony style (`$foo = 'bar'.$bar;`)

**Comment by bobdenotter** [comment]
- [x] One space, Bolts **current** style (`$foo = 'bar' . $bar;`)
- [ ] No space, Symfony style (`$foo = 'bar'.$bar;`)

**Comment by rixbeck** [comment]
+1 for space

Sent with AquaMail for Android
http://www.aqua-mail.com

**Comment by rarila** [comment]
As it's `1 + 2` I think its consistent to have `'foo' . 'bar'`
- [X] One space, Bolts whatever style ($foo = 'bar' . $bar;)
- [ ] No space, Symfony style ($foo = 'bar'.$bar;)

**Comment by GwendolenLynch** [comment]
Superseded by #5

**Pull request closed without merging**
